server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://dpg-ch895aesi8uhth5qr77g-a.oregon-postgres.render.com:5432/petzzz
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true